### ISSUE TITLE
GitHub Actions core library version has vulnerability

### ISSUE THREAD

**Issue by peter-murray** [google-github-actions/setup-gcloud#225]
### TL;DR

As of November 16th 2020, the actions contained in this repository will stop working as some of them are using a vulnerable version of the @actions/core npm module; https://github.com/google-github-actions/setup-gcloud/blob/0.1.3/setup-gcloud/package.json#L31

See https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/ for more details.

We need updated versions published so that these actions will continue to function after the 16th November 2020 when GitHub disables the old behaviour this and closes the vulnerability.

**Comment by averikitsch** [comment]
Thanks for your report. The master branch has been updated with this change. We will be cutting a new release shortly. For now please target `@master` not version `@0.1.3`.
