### ISSUE TITLE
Old examples instead of new ways of using the refactored actions.

### ISSUE THREAD

**Issue by vicpara** [google-github-actions/setup-gcloud#243]
### TL;DR
All examples provided in this repo are still using the old example from `GoogleCloudPlatform/github-actions/setup-gcloud`

**Expected behavior**
All examples are relevant for the new way of using the action.

**Observed behavior**
Nobody bothered checking.

### Reproduction
https://github.com/google-github-actions/setup-gcloud/blob/master/example-workflows/gke/.github/workflows/gke.yml

**Comment by averikitsch** [comment]
Fixed by #250
