### ISSUE TITLE
Add an example for handling environment variables or secrets

### ISSUE THREAD

**Issue by benjamintd** [google-github-actions/setup-gcloud#249]
The current example workflows do not describe how to use Github's secrets (repository environment variables) when building and deploying to Cloud Run. 

It would be nice to have an example which passes environment variables or secrets to the build step, as I have found this step to be rather confusing. 

Thank you for those examples, they are already very helpful.

**Comment by averikitsch** [comment]
Hi @benjamintd , the [build step](https://github.com/google-github-actions/setup-gcloud/blob/master/example-workflows/cloud-run/.github/workflows/cloud-run.yml#L48) does use environment variables. The env vars are set at the top of the workflow:
```
env:
  PROJECT_ID: ${{ secrets.RUN_PROJECT }}
  RUN_REGION: us-central1
  SERVICE_NAME: helloworld-nodejs
```
and then referenced in the build:
```
 - name: Build
    run: |-
        gcloud builds submit \
          --quiet \
          --tag "gcr.io/$PROJECT_ID/$SERVICE_NAME:$GITHUB_SHA"
```

Is there a specific I can help you with?

**Comment by awhisler** [comment]
@averikitsch this doesn't seem to work anymore
<img width="768" alt="image" src="https://github.com/user-attachments/assets/c3f296c8-fb99-4513-8566-3b381d46f248">
