### ISSUE TITLE
Improve error message for malformed JSON key

### ISSUE THREAD

**Issue by Albinzr** [google-github-actions/setup-gcloud#261]
Im getting **Error: Unexpected token � in JSON at position 0** at the end 
is this a bug if not can anyone help me with this issue?
![Screen Shot 2021-01-11 at 12 19 38 AM](https://user-images.githubusercontent.com/7425577/104132371-d77c7f80-53a2-11eb-8e2f-d470ca85f244.png)

**Comment by monotek** [comment]
How have you fixed it?
Suddenly my pipeline fails with this too.

**Comment by averikitsch** [comment]
This error comes from a malformed service account key. Please make sure it is valid JSON. I am reopening this bug in order to add a better error message.

**Comment by monotek** [comment]
The weird thing is that my working pipline fails all of a sudden.
Used a base64 encoded json and changed it now to plaintext but still fails :/
Any way to add debug output?

**Comment by Albinzr** [comment]
@averikitsch  @monotek Have tried creating a service account JSON key file and replacing the old one with (use complete JSON)

**Comment by patotoma** [comment]
just spent few hours on this also
