### ISSUE TITLE
Just wanted to say thanks! 

### ISSUE THREAD

**Issue by twosdai** [google-github-actions/setup-gcloud#263]
### Question

Just wanted to say thanks for maintaining this repo and documentation. It was really helpful for me when I was setting up a project for Kubernetes in Google Cloud. I was able to get up and running in ~30 minutes with limited kubernetes/docker experience. Keep up the awesome work. :) 

Referencing this topic: https://github.com/compumike/hairpin-proxy/issues/5 / https://news.ycombinator.com/item?id=25551487

**Comment by bharathkkb** [comment]
Thanks for the wonderful note @twosdai Glad to hear this has been helpful!

**Comment by tequilarista** [comment]
as much as it pains, will close this out, but thanks again for the feedback
