### ISSUE TITLE
Why is no official link to Google / GCP?

### ISSUE THREAD

**Issue by botic** [google-github-actions/setup-gcloud#267]
### Question

I ran into Github Actions for one of our Open Source projects and saw this _google-github-actions_ organization in various tutorials. But it took me some minutes to find out if this is an official organisation run by Google, or not. You should provide additional information in the repositories (e.g. "Github action for App Engine, provided by Google") and update this organization's metadata / links. At least some public members could increase the trust, too.

#### Current State

<img width="1091" alt="grafik" src="https://user-images.githubusercontent.com/193023/107379934-b3b97000-6aed-11eb-98c5-027ee3a17b00.png">

#### Google's Organization

<img width="1091" alt="grafik" src="https://user-images.githubusercontent.com/193023/107380377-1b6fbb00-6aee-11eb-8ec4-696bb96da3e9.png">

**Comment by mirzawaseembaig** [comment]
Hi whats new on github , plz send me feed back , about this information

**Comment by bharathkkb** [comment]
Hi @botic 
Thanks for the issue, we are currently working to get this verified and update the metadata.

**Comment by botic** [comment]
> Thanks for the issue, we are currently working to get this verified and update the metadata.

Perfect! So time to get into deploying my App Engine applications on push :)

**Comment by iennae** [comment]
Thanks for reaching out! As of today we're verified. 
![Screen Shot 2021-07-14 at 7 41 16 PM](https://user-images.githubusercontent.com/1592404/125719717-0bc2c462-8d56-4089-bd5b-31258b2a12d7.png)
