### ISSUE TITLE
Getting repository not found

### ISSUE THREAD

**Issue by yrashish** [google-github-actions/setup-gcloud#270]
Failed to resolve action download info. Error: Unable to resolve action `GoogleCloudPlatform/google-GitHub-actions@master`, repository not found.

I am guessing it has something to do with Github runners. Not sure why I suddenly started getting this error.

Here is my workflow.
https://github.com/yrashish/indian-states/blob/master/.github/workflows/main.yml

Pipeline logs:
https://pipelines.actions.githubusercontent.com/123kKbv6EM4ktfRwTz3sv6Xs3JHNXYfokd6HcKd1u3UNm14Amd/_apis/pipelines/1/runs/32/signedlogcontent/3?urlExpires=2021-03-10T19%3A34%3A55.5547168Z&urlSigningMethod=HMACV1&urlSignature=LkvhDwZCv4xlN1eLgFv5i5womM7xcjn09bqi9o22g4I%3D

**Comment by averikitsch** [comment]
Hi @yrashish , Please update your workflow to use `google-github-actions/setup-gcloud@master`.

**Comment by yrashish** [comment]
Thanks, @averikitsch. I am getting this error now instead.
ERROR: (gcloud.container.clusters.get-credentials) ResponseError: code=403, message=Required "container.clusters.get" permission(s) for "projects/***/zones/us-central1-c/clusters/***"

**Comment by averikitsch** [comment]
Make sure your service account key that you use to authenticate the `setup-gcloud` action has permissions for ["container.clusters.get"](https://cloud.google.com/iam/docs/permissions-reference); for example the role Kubernetes Engine Developer (roles/container.developer) has these permissions.
