### ISSUE TITLE
Make base URL configurable

### ISSUE THREAD

**Issue by thomasmey** [google-github-actions/setup-gcloud#328]
Hi,

when running on a self-hosted github action runner it would be nice to make this hard coded base URL configurable, so this can be set to a "local" mirror instead of downloading this each time form the internet:

https://github.com/google-github-actions/setup-gcloud/blob/27891cab69c20381eb97f14af66c40596fed56f2/setupGcloudSDK/src/format-url.ts#L50

**Comment by bharathkkb** [comment]
Thanks for the FR @thomasmey 
Happy to review a PR if you have a chance.
