### ISSUE TITLE
Support gcloud alpha / beta

### ISSUE THREAD

**Issue by ocervell** [google-github-actions/setup-gcloud#330]
Currently, I have to run `gcloud components update` in order to run `gcloud alpha` and `gcloud beta` commands. Maybe we could add a flag to automatically get those ?

**Comment by bharathkkb** [comment]
@ocervell 👋 
We are looking into supporting this soon. /cc @averikitsch

**Comment by erzz** [comment]
any update?

**Comment by sethvargo** [comment]
Duplicate of https://github.com/google-github-actions/setup-gcloud/issues/103
