### ISSUE TITLE
Getting 'The user is forbidden from accessing the bucket [presto-operator_cloudbuild]'

### ISSUE THREAD

**Issue by Ayan07** [google-github-actions/setup-gcloud#364]
I am getting the following error while I try to run the command 
'gcloud builds submit --config steerdpresto.yaml'

Error:
'(gcloud.builds.submit) The user is forbidden from accessing the bucket [presto-operator_cloudbuild]. Please check your organization's policy or if the user has the "serviceusage.services.use" permisison.'

My **steerdpresto.yaml** file:
steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/steerd-presto-operator', '-f', 'docker/Dockerfile', '.']
images:
  - 'gcr.io/$PROJECT_ID/steerd-presto-operator'
  
  
PROJECT_ID: presto-operator

**Comment by averikitsch** [comment]
Closing. Please reopen if you are still experiencing this issue.
