### ISSUE TITLE
Refactor integration test gating

### ISSUE THREAD

**Issue by bharathkkb** [google-github-actions/setup-gcloud#414]
To consider in a follow-up. I wonder if we can store this conditional as an [env](https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions#env) and then just reference the `env` in the conditional instead. I think:

```yaml
if: ${{ env.CAN_ACCESS_SECRETS }}
```

might be a little clearer. Alternatively, maybe we could do something with [defaults](https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions#defaults) to have a default `if`?

Low priority, just thinking out loud.

_Originally posted by @sethvargo in https://github.com/google-github-actions/setup-gcloud/pull/413#discussion_r761176905_

**Comment by sethvargo** [comment]
I tried it out, sadly it doesn't work.
