### ISSUE TITLE
Building GCP Function as part of the deployment action

### ISSUE THREAD

**Issue by max-toepfer** [google-github-actions/setup-gcloud#503]
### TL;DR

The deploy-cloud-functions action should also cater for the building of the source code package with regards to the dependencies, i.e., if there is a requirements.txt in the code directory, the respective packages should be included in the build uploaded to GCP.

### Detailed design

```markdown
A simple input flag to turn the building off or on would suffice, I suppose.
```

**Comment by sethvargo** [comment]
Hi @max-toepfer 

I'm not sure I understand the request. Cloud Functions _are_ built as part of the deployment. This is handled by Cloud Functions natively.

Are you experiencing something different? If so, could you please provide an Action YAML?

Do also note, you filed an issue against [setup-gcloud](https://github.com/google-github-actions/setup-gcloud). The GCF action is at [deploy-cloud-functions](https://github.com/google-github-actions/deploy-cloud-functions).

**Comment by max-toepfer** [comment]
@sethvargo , my bad! I'll fix that.
