### ISSUE TITLE
On 2022-04-05, the default branch will be renamed from "master" to "main"

### ISSUE THREAD

**Issue by sethvargo** [google-github-actions/setup-gcloud#539]
> On 2022-04-05, the default branch will be renamed from "master" to "main". Your action is currently pinned to "@master". Even though GitHub creates redirects for renamed branches, testing found that this rename breaks existing GitHub Actions workflows that are pinned to the old branch name.
>
> We strongly advise updating your GitHub Action YAML from:
>
>     uses: 'google-github-actions/setup-gcloud@master'
>
> to:
>
>     uses: 'google-github-actions/setup-gcloud@v0'
>
> While not recommended, you can still pin to the "master" branch by setting the environment variable "SETUP_GCLOUD_I_UNDERSTAND_USING_MASTER_WILL_BREAK_MY_WORKFLOW_ON_2022_04_05=1". However, on 2022-04-05 when the branch is renamed, all your workflows will begin failing with an obtuse and difficult to diagnose error message.

This error message means your GitHub Action is currently pinned to `@master`. As noted in the error, you can update your action to pin to `@v0` instead. You can also pin to a specific Git SHA or tag.

On April 4th, 2022, we will rename the default branch from "master" to "main". While GitHub will properly configure redirects, our [previous testing](https://github.com/google-github-actions/setup-gcloud/issues/451) found that GitHub Actions does not respect this redirect. Instead of leaving users with a confusing error message, we've added this explicit error message.

### FAQ

**Why is this change necessary?**<br>In order to be as inclusive as possible, all the default branches for our GitHub Actions repositories are named `main`. The `setup-gcloud` action predates this change. Having some repos use `master` and some use `main` is confusing for users, so we are standardizing on `main` moving forward.

**Couldn't you have issued a warning instead of throwing an error?**<br>We have been printing a warning message [since December 29](https://github.com/google-github-actions/setup-gcloud/commit/1a48ffaf046b28c93468eef7603c643377f487ec).

**Should I pin to `@v0`?**<br>[We recommend](https://github.com/google-github-actions/setup-gcloud#versioning) pinning to the latest major version. This will ensure you get all new features and bug fixes while _minimizing_ the chances of a breaking change. At this time, the latest major version is `v0`. If you are concerned about breaking changes or security, you should pin to a specific Git SHA instead.

**Comment by bc185168** [comment]
Really slick to do this after work hours, but some of us have offshore devops engineers who are all asleep. Now we can't run builds.

**Comment by sethvargo** [comment]
> Really slick to do this after work hours, but some of us have offshore devops engineers who are all asleep. Now we can't run builds.

Thank you for the feedback @bc185168. We're trying to be as non-invasive as possible. If we did this during "Atlanta" time, it would be the middle of the night for Europe and Asia. There's never a convenient time 😦.

**Comment by Alexandru-Dobre** [comment]
While I understand the reasons behind the naming changes I don't think breaking builds is the right call. Improving GitHub Actions  to get it to properly follow the redirect or making copy of the @v0 branch called "master" would have avoided builds breaking all over the world and people scrambling to fix them. Breaking changes should only be made in the event of a critical security issue as they can have severe consequences on business.

**Comment by savvaki** [comment]
What an unprofessional way of breaking everyone's integration.

**Comment by andoshin11** [comment]
Our entire product codebase and build pipeline is now broken.

Personally I was fine with this whole mumbles about `main` or `master`, even though it totally seemed nothing but a hypocrisy. However I think the way you pushed your **idea** is absurd and extremely careless.

**Comment by cpoissonnier** [comment]
When we update the action version from `main` to `v0`, we have a `GitHub Actions has encountered an internal error when running your job.`. Everything was working perfectly fine before.
Is there something else to update in our workflows?

**Comment by erwanriou** [comment]
Honestly you are aware you just broke around 5000 pipelines and i have to change them all manually now, great! Creating new projects with `main` was completely fine but forcing to update old ones that is not nice! 
Have you more surprises like this one? Do you really think it help the cause in anyway?

**Comment by bc185168** [comment]
> We have been printing a warning message [since December 29]

If a pipeline will fail, it should fail on 2022-04-05, not 2022-03-21

**Comment by jacderida** [comment]
It's hard to think of another social justice cause that had so much effort for such little impact.

**Comment by ftpd** [comment]
And the worst thing in this is: Black Community, which is marked as 'offended', doesn't give a single damn how github (or whatever) calls the main/master/most_important/root branch. Yet another white people decided for Blacks what they want. Sad.

**Comment by adesnmi** [comment]
> And the worst thing in this is: Black Community, which is considered 'offended' in such cases, doesn't give a single damn how github (or whatever) calls the main/master/most_important/root branch. Yet another time white people decided for Blacks what they "want". Sad.

I wasn't aware you were a spokesperson for the entire black community. I must have missed your anointment.

**Comment by adesnmi** [comment]
> Black Community, which is considered 'offended' in such cases, doesn't give a single damn how github (or whatever) calls the main/master/most_important/root branch

1. I can understand if you have an opinion against Github renaming a branch by default, just don't claim to speak for everyone within a community. I know black people who don't care and many who do.

2. This is Google making a decision themselves, not claiming to speak for a specific community.

**Comment by sethvargo** [comment]
> While I understand the reasons behind the naming changes I don't think breaking builds is the right call. Improving GitHub Actions to get it to properly follow the redirect or making copy of the @v0 branch called "master" would have avoided builds breaking all over the world and people scrambling to fix them. Breaking changes should only be made in the event of a critical security issue as they can have severe consequences on business. - @Alexandru-Dobre

@Alexandru-Dobre thank you for the suggestion. We have raised this issue with GitHub and the GitHub Actions team. They believe the current implementation is working as intended. Please keep in mind that we are not the GitHub Actions team and we have no control over how GitHub Actions behaves or resolves references.

Leaving a dangling `master` branch would have kept builds working, but that branch would have become stale and stagnant over time. Given the number of software supply chain and security issues, this did not feel like an appropriate path. Furthermore, creating a branch named "master" would break the redirect GitHub installs when a branch is _renamed_.

> What an unprofessional way of breaking everyone's integration. - @savvaki

@savvaki - Thank you for the feedback. If you have alternative ideas, we're always open to exploring other options. Our team has been debating this change for many months. Our original attempt of renaming the branch in December [broke with unintuitive and confusing error messages](https://github.com/google-github-actions/setup-gcloud/issues/451). The goal here is to provide a helpful and actionable error message for users.

> Our entire product codebase and build pipeline is now broken. - @andoshin11

@andoshin11 - Sorry 😦. We've tried very hard to message this over the past 3 months, emitting warning messages. Please also note that it appears [GitHub Actions also appears to be having issues](https://www.githubstatus.com/incidents/sks5ctnwcxsb), which is unrelated to our change. If you are seeing general build failures, it might be due to the GitHub issue.

> Honestly you just broke all my pipelines and i have to change them all manually now, great! - @erwanriou

@erwanriou - Sorry about that. We've tried very hard to message this over the past 3 months, emitting warning messages. We did check how many pipelines we would break, and I personally submitted over 100 PRs to the top repositories. However, we can only check _public_ repositories. We have no way of emailing maintainers. Please keep in mind that we are not the GitHub Actions team - we merely publish a GitHub Action for interacting with Google Cloud. If we had the information you suggested, we definitely would have used it.

As far as updating `master` -> `main`, we haven't made the change yet. The default branch is still named "master", but it throws this error when the GitHub Action is pinned to "master". On 2022-04-05, we are going to rename the branch from "master" to "main". At that point, we can no longer provide an informative and actionable error message, because the GitHub Action will fail at the control plane layer at GitHub (our code will not be invoked). This is what happened when we [tried to rename the branch last year](https://github.com/google-github-actions/setup-gcloud/issues/451). To avoid non-actionable error messages, we're introducing this informative error, largely to echo your point about the warning message. The only mechanism we have to get users to pay attention is to throw errors.

> If a job will fail, it should fail on 2022-04-05, not 2022-03-21 - @bc185168

@bc185168 - If we just renamed the branch on 2022-04-05, we would be replaying the [December rename attempt](https://github.com/google-github-actions/setup-gcloud/issues/451). 

> guys this is not about master or main branches or github. This is about google been unprofessional in their way they handle their own changes. The branches of my crashed repositories where already using main in fact. - @erwanriou

@erwanriou = Could you please share more information? In our testing and in reviewing the code, you should only get this error if you're using `google-github-actions/setup-gcloud@master`. There is no `main` branch for this GitHub Action yet, and we [advise against pinning to HEAD](https://github.com/google-github-actions/setup-gcloud#versioning).

---

Please try to keep conversation civil. Comments not in line with [Google's Code of Conduct](https://opensource.google/documentation/reference/releasing/template/CODE_OF_CONDUCT) are not tolerated.

**Comment by pmeredit** [comment]
I wonder if I need to change my MS diploma from Master of Science to Main of Science to be more inclusive?

**Comment by stack72** [comment]
@sethvargo thanks for the heads up on this change! I am happy you were able to give me time to fix this up!

**Comment by andoshin11** [comment]
I'm deeply disappointed that the only excuse Google came up with is just "we've been trying very hard". What an irresponsible way for such a tech giant.

Man, just go ask some of those thousands of users whether if they were aware of the the change and its impact, and you'll see what I mean.

**Comment by andoshin11** [comment]
@sethvargo 

> Please also note that it appears [GitHub Actions also appears to be having issues](https://www.githubstatus.com/incidents/sks5ctnwcxsb), which is unrelated to our change. If you are seeing general build failures, it might be due to the GitHub issue.

Nah, it ain't GitHub's fault. I checked the stack trace and pretty sure it was an error thrown by this GA.

**Comment by marcusziade** [comment]
This process is unprofessional behavior. You're better than this

**Comment by mgeisler** [comment]
> Since the redirect in GitHub Actions does not currently work then there should be no harm in keeping a branch called master temporarily. Yes, it will grow stale over time, but not more so than any tag and it should be possible to delete it once the redirect is fixed or another solution is found.

The easy thing to do would be to have both. Branches are cheap and writing a script to keep `master` in sync with the a _new_ `main` branch is easy. So no remaining, full compatibility with old and new workflows.

All that was needed was to update all documentation to refer to `main` instead of `master` going forward.

Not breaking builds should be the prime objective of a GitHub Action, and keeping `master` around would accomplish that.

**Comment by Alexandru-Dobre** [comment]
The main reason of investing into Google Cloud services was to ensure smooth and incident-free operation of our deployments and pipelines. The last thing we expected was for Google Cloud's Engineers to intentionally cause such an incident and to respond in such an unprofessional way to the complaints of their clients.

As others have pointed out, this was far from unavoidable and there was never any communication mentioning the date of 21 March.  Furthermore, it is extremely unprofessional and condescending to attempt to shift the blame on your clients for not "paying attention".

We will not be gaslit into believing it is acceptable for our pipelines to be intentionally disabled or that our only recourse in such an incredible situation is to fix them ourselves on our own time and money and move on.  

I believe the right move would be to remove the intentional blocker currently breaking everyone's pipelines and to refrain from any further action that would break any workflow. 

As this has been going on for two working days with no end in sight, the next logical step would be to file a complaint with Google Cloud in order to further escalate the issue. That seems to be the only way for us, clients, to get Google Cloud's engineers to "pay attention".

**Comment by tyriis** [comment]
I like the environment variable name :)

**Comment by ShayanBozorgmehri** [comment]
FFS. Do you guys really think your little SJW change here is actually going to solve any real world issues? If so, then you guys are might want to go see a psychologist. 

You want real, good change? Go fight against actual inequality in third world countries.

**Comment by jamesmortensen** [comment]
Isn't this action deprecated?  We were getting warnings to switch to google-github-actions/auth, so we did...

**Comment by sethvargo** [comment]
Hi @jamesmortensen - the setup-gcloud action isn't deprecated, but the "authentication" features are deprecated.

- `auth` - authenticate to google cloud for future steps
- `setup-gcloud` - install the `gcloud` CLI tool

**Comment by nsjames** [comment]
I think along the way we've forgotten that backwards support for public services is imperative. Tooling like this must follow the browser update ethics which state that all previous features must be supported indefinitely, for better or worse. 

This isn't some internal company tool, it's one that is integrated into many others with no proper way for you to contact them. Knowing that circumstance the master branch should have been locked at its current version and kept as archived after switching to a main branch, with warnings of depreciation left in the logs. Breaking every single integrator's CI should never have been the way to go, or even an option. 

I'm disappointed that this was the choice that was made, and you should be too.

**Comment by Xunjin** [comment]
I wonder how many of you would have actually seen this change in the date 2022-04-05 and fix before messing your CIs :sweat_smile: 

Of course this was not expected, and I do understand all the points of view as well the complaints. Doesn't mean that I actually agree, this issue is actually starting to being toxic and should be locked by now. (Of course I'm a nobody, so my opinions shouldn't mean a s*** for you).

If you believe that this project is not any more reliable to put in your CIs, just fork it and make one that you trust :)

That's the beauty of OSS.

**Comment by lucjross** [comment]
i don't know why this is such a big deal to people. just search your repositories for the action name and replace usages. why would you use a branch tag instead of a version tag anyway

**Comment by therealbluepandabear** [comment]
Google is so woke that it's actually funny -- thinking changing a virtual branch name is 'inclusive'. What a crappy, deranged silicon valley company.

**Comment by therealbluepandabear** [comment]
> I wonder how many of you would have actually seen this change in the date 2022-04-05 and fix before messing your CIs 😅
> 
> Of course this was not expected, and I do understand all the points of view as well the complaints. Doesn't mean that I actually agree, this issue is actually starting to being toxic and should be locked by now. (Of course I'm a nobody, so my opinions shouldn't mean a s*** for you).
> 
> If you believe that this project is not any more reliable to put in your CIs, just fork it and make one that you trust :)
> 
> That's the beauty of OSS.

Sure, we can make a fork. But we can also point out the ridiculousness in stating that changing a VIRTUAL branch name can bring about more 'inclusivity'.
