### ISSUE TITLE
Support for gcrane

### ISSUE THREAD

**Issue by iuadastra** [google-github-actions/setup-gcloud#547]
### TL;DR

Add support for gcrane https://github.com/google/go-containerregistry/tree/main/cmd/gcrane

### Additional information

When doing multi-project deployment it would be useful to have the possibility to copy (docker) images between projects. This can be done via gcrane

**Comment by sethvargo** [comment]
Hi @iuadastra 

Thanks for opening an issue. gcrane is independent from gcloud, so I don't think it makes a ton of sense to have it as part of the `setup-gcloud` command. We could investigate creating a new command, or just leveraging a composite command that uses go and installs gcrane at a specific version.

**Comment by sethvargo** [comment]
Hi @iuadastra 

It would be best to raise this request with the gcrane team to see if they are interested in building or maintaining this.
