### ISSUE TITLE
Group Tar output in github logs

### ISSUE THREAD

**Issue by nyarly** [google-github-actions/setup-gcloud#557]
### TL;DR

Currently, any job that uses google-github-actions/setup-gcloud gets spammed with the tar output of unpacking the gcloud archive. While this might sometimes be crucial for debugging, it's a real hassle when CI issues aren't related to setup-gcloud

### Detailed design

```markdown
_a la_ https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#grouping-log-lines : 


echo ::group::GCloud tar unpack
/usr/bin/tar xz -v --warning=no-unknown-keyword --overwrite -C <tmp1> -f <tmp2>
echo ::endgroup::
```
```


### Additional information

This'd be really easy to do. I'd provide the PR if it'd be accepted

**Comment by sethvargo** [comment]
Hi @nyarly 

Feel free to take a stab, but I'm fairly certain that log output comes from [actions/tool-cache](https://github.com/actions/toolkit/tree/master/packages/tool-cache).
