### ISSUE TITLE
Looks like 0.6.2 hasn't been released.

### ISSUE THREAD

**Issue by Byeong-jun-Kim** [google-github-actions/setup-gcloud#578]
### TL;DR

https://github.com/google-github-actions/auth/issues/235
As I mentioned here, it looks like 0.6.2 hasn't been released.

https://github.com/marketplace/actions/set-up-gcloud-cloud-sdk-environment
<img width="1031" alt="image" src="https://user-images.githubusercontent.com/75416321/197860122-c4501315-01e5-429a-af27-006cdfa3777c.png">

### Action YAML

```yaml
- name: Setup gcloud cli
    uses: google-github-actions/setup-gcloud@v0.6.0
```

**Comment by sethvargo** [comment]
Fixed
