### ISSUE TITLE
Getting a 404 when trying to use this

### ISSUE THREAD

**Issue by kingpinzs** [google-github-actions/setup-gcloud#617]
### TL;DR

Getting a 404 when trying to use this

  - name: Install Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1.1.0

### Expected behavior

install google sdk

### Observed behavior

cant find it

### Action YAML

```yaml
- name: Install Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1.1.0
```

### Log output

```text
Error: google-github-actions/setup-gcloud failed with: unexpected HTTP response: 404
```

**Comment by sethvargo** [comment]
Hi there - could you please provide the [debug output](https://docs.github.com/en/actions/monitoring-and-troubleshooting-workflows/enabling-debug-logging) for the complete GitHub Actions workflow run?

**Comment by sethvargo** [comment]
Closing due to lack of response. If this is still happening, please open a _new_ issue with the debug logs.
