### ISSUE TITLE
Authentication using Application Default Creds does not export creds in subsequent steps

### ISSUE THREAD

**Issue by loayei** [google-github-actions/setup-gcloud#619]
### TL;DR

I am authenticating into setup-gcloud using Application default credentials because am running a self hosted runner on GCP.
I am trying to run helm gcs init command but it is not running and am getting permission denied.

Is it something wrong am doing or I do need to run the auth action and pass a key or workload identity to run helm gcs command.

**Comment by loayei** [comment]
Its actually in storage buckets. so am getting a storage.object permission error.

does auth support application default credentials ? I tried it and it fails

**Comment by sethvargo** [comment]
It's very difficult to debug these kinds of things when you bypass the issue template. Please provide your complete Action YAML, and the [debug log output](https://docs.github.com/en/actions/monitoring-and-troubleshooting-workflows/using-workflow-run-logs#downloading-logs).

**Comment by loayei** [comment]
Thanks for your response i was able to figure it out. I was not giving the runner service account the required permissions.
Thanks again
