### ISSUE TITLE
Unable to push the branch and create PR

### ISSUE THREAD

**Issue by rtrzebinski** [google-github-actions/setup-gcloud#626]
Hi, I wanted to submit a PR with some fixes to `https://github.com/google-github-actions/setup-gcloud/tree/main/example-workflows/gke`, but I'm getting this on push:

```
setup-gcloud $ git push --set-upstream origin gke-fixes
ERROR: Permission to google-github-actions/setup-gcloud.git denied to rtrzebinski-usc.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists
```

**Comment by sethvargo** [comment]
Hi @rtrzebinski 

Please see our [contributing guide](https://github.com/google-github-actions/.github/blob/main/CONTRIBUTING.md#development-model). Outside collaborators cannot push changes to this repo. You must fork and submit a pull request. For more information, see the GitHub [documentation on submitting a pull request](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request-from-a-fork).
