### ISSUE TITLE
Request timeout when downloading gcloud sdk

### ISSUE THREAD

**Issue by tomorr-rexhepi** [google-github-actions/setup-gcloud#680]
### TL;DR

There is a request timeout when attempting to download gcloud sdk.

### Expected behavior

gcloud sdk to download

### Observed behavior

The request timed out while downloading: /dl/cloudsdk/channels/rapid/downloads/google-cloud-sdk-463.0.0-linux-x86_64.tar.gz

### Action YAML

```yaml
name: 'REDACTED'
description: 'REDACTED'
runs:
  using: "composite"
  steps:
    - id: setup-gcloud
      uses: google-github-actions/setup-gcloud@v2.1.0
```

### Log output

```text
##[debug]resolving latest version
##[debug]resolved latest version to 463.0.0
##[debug]isExplicit: 463.0.0
##[debug]explicit? true
##[debug]checking cache: /opt/hostedtoolcache/gcloud/463.0.0/x64
##[debug]not found
##[debug]no version of gcloud matching "463.0.0" is installed
##[debug]isExplicit: 463.0.0
##[debug]explicit? true
##[debug]Downloading https://dl.google.com/dl/cloudsdk/channels/rapid/downloads/google-cloud-sdk-463.0.0-linux-x86_64.tar.gz
##[debug]Destination /runner/_work/_temp/e79beb02-7b67-[42](REDACTED)8c-b3d6-a0f42cf88013
Request timeout: /dl/cloudsdk/channels/rapid/downloads/google-cloud-sdk-[46](REDACTED)3.0.0-linux-x86_64.tar.gz
Waiting 14 seconds before trying again
Request timeout: /dl/cloudsdk/channels/rapid/downloads/google-cloud-sdk-463.0.0-linux-x86_64.tar.gz
Waiting 17 seconds before trying again
Error: google-github-actions/setup-gcloud failed with: request timeout: /dl/cloudsdk/channels/rapid/downloads/google-cloud-sdk-463.0.0-linux-x86_64.tar.gz
```

**Comment by sethvargo** [comment]
Hi @tomorr-rexhepi - is this happening consistently? Are you using GitHub-managed runners or self-hosted runners?

**Comment by tomorr-rexhepi** [comment]
Hi @sethvargo - it's happening consistently and we are using self-hosted runners.

**Comment by sethvargo** [comment]
Given there are no other reports, this is most likely a proxy or egress firewall configuration on your self-hosted runners.

**Comment by tomorr-rexhepi** [comment]
Perhaps, but the older versions were working fine - the ones using node16. This error only occurs with the v2 versions. What change could've caused this problem to now appear on v2?

**Comment by sethvargo** [comment]
Not unless there were core Node.js changes to proxy configurations between those versions.
