### ISSUE TITLE
What is the release cycle for this project?

### ISSUE THREAD

**Issue by michellen-hf** [google-github-actions/setup-gcloud#93]
### Question
It's been over a month since setting a `project_id` has been added to `setup-gcloud`.  I was wondering when the next release would be cut as that's a feature I'd like to have but don't want to use `master` in production projects.

**Comment by sethvargo** [comment]
Hi @michellen-hf - to clarify. Are you asking us to tag a new version?

**Comment by michellen-hf** [comment]
That would be awesome!
But It would also be nice to know what the overall release cycles will be for this project if you have thought about it. It's an incredibly helpful project and lots of new features are being added fairly often.

**Comment by sethvargo** [comment]
@craigdbarber thoughts on a release cadence

**Comment by tequilarista** [comment]
Hey @michellen-hf!  At the moment we have no plan, but we are definitely talking about it.  There are a couple of weird things we're currently dealing with around version tagging on the various actions that aren't ideal and I suspect that figuring that out will be a precursor to any other moves around release schedules.  Cheers!

**Comment by michellen-hf** [comment]
Sounds good!

I've been using @master for now without an issue, but I'd appreciate even a moving tag for something like @v1 if that helps with your versioning concerns!

Thanks for all the hard work!
Feel free to close this ticket now or leave it open till you figure out the plan.

**Comment by tequilarista** [comment]
Assigning to Craig to close once a path is decided

**Comment by michellen-hf** [comment]
I'd like to bump this.
I'd love a moving tag/branch so that way I can stick to just @v1 versions of these actions. I'm pushing fairly sensitive resources to GCP and don't want to have some unexpected breaking upgrade only partially break my workflows.

An example of one that was ALMOST very bad for our team - docker/build-push-action v2 action ignored the credentials set by setting `_json_key`  + google credentials, and pushed by default to the main public docker repo. I understand that there might not be a current plan to make breaking changes but I'd feel very reassured if we could explicitly say that "v2"/breaking changes need manual intervention!

**Comment by bharathkkb** [comment]
Hi @michellen-hf 
Thanks for the feedback, we have been working on splitting up our action repos to enable the moving tags more easily. This is something we are going to prioritize next.

**Comment by bharathkkb** [comment]
x-ref: https://github.com/google-github-actions/release-please-action/issues/91
